secure:
  ignored:
    urls:
      - /swagger-ui/
        - /swagger-resources/**
        - /**/v2/api-docs
        - /**/*.html
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.map
        - /favicon.ico
        - /actuator/**
        - /druid/**
        - /admin/login
        - /admin/register
        - /admin/info
        - /admin/logout
        - /minio/upload